### ISSUE TITLE
[Linux/AppImage] App silently fails when drag-and-drop a selected text

### ISSUE THREAD

**Issue by Brootux** [iotaledger/trinity-wallet#303]
### Bug description
If we drag any selected text in any textbox, and drop the text inside or outside of the app, it freezes and only is killable via ctrl-c in terminal. If killed via `kill -9 [pid]` there are still some mounts in /tmp left (seems like appimage magick) and the GUI is still open.

### Environment Specs
What device are you running Trinity on?

- Manufacturer: Lenovo
- Model: Thinkpad T420
- OS version: Ubuntu 18.04

What build of Trinity are you running? Please provide the full version (you can find it in Settings > About Trinity).

- Trinity version: v0.3.2

### Steps To Reproduce
1. open any page with a textfield
2. may type something into
3. select text
4. drag-and-drop selected text anywhere

### Expected behaviour
Text was moved/copied or nothing happened

### Actual behaviour
- App freezes
- no error message in stdout
- no error message in error-log after app restart

### Errors
No Error messages or logs (may will retry with a debug build, if i find out how to build one ;)

**Comment by Brootux** [comment]
Note: when the default ubuntu dialog "application does not respond" dialog appears on top of the app, ill cannot interact with any other running app (i.e. browser). This seems more like a ubuntu bug(?).

**Comment by rajivshah3** [comment]
Hi @Brootux , does running Trinity with `--disable-gpu` help? See https://github.com/electron/electron/issues/12820

> may will retry with a debug build, if i find out how to build one

You can build Trinity yourself by following these steps: https://github.com/iotaledger/trinity-wallet/tree/develop/src/desktop#building-the-application. In step 4, run `npm run compile:linux`

**Comment by Brootux** [comment]
@rajivshah3 yes with `--disable-gpu` the problem disappears. So if its a known bug, we may can close this.

**Comment by rajivshah3** [comment]
@Brootux the `--disable-gpu` option is a workaround, but ideally there should be a solution to this. I'll keep looking into it

**Comment by delki8** [comment]
@Brootux can you please check if I did the right steps to reproduce the bug? I recorded this video https://vimeo.com/290608713 trying to reproduce it.

**Comment by rajivshah3** [comment]
@delki8 @Brootux this is likely a bug upstream. If you guys are willing to help `electron` solve the issue, it might help if you posted your repro steps and environment details (especially GPU - this sounds like it might be GPU-specific issue) on https://github.com/electron/electron/issues/12820. Unfortunately I don't have a Linux VM so I can't be of much help. I'll also ask around on Discord to see if anyone else can reproduce this issue.

**Comment by Brootux** [comment]
@delki8 i think the steps are correct, ill did not drop it into a editor or something. I can make a video later this day (after work).

@rajivshah3 my T420 only has some intel graphics inside, will check exact model and post it here and in the electron issue. Also will check on another linux box.

**Comment by Brootux** [comment]
Tested on another linux box with nvidia graphics -> no problem.

**Comment by rajivshah3** [comment]
@Brootux aha - must be the Intel. In the thread I linked to above, there are two others with Intel HD Graphics who are having issues. Unfortunately I don’t think there’s much that can be done on the Trinity side to fix this, but I’ll leabe this issue open until we upgrade to a version of Electron that fixes this

**Comment by delki8** [comment]
@Brootux and @rajivshah3, I don't think that the problem is with the Intel graphics, I forgot to tell you that my video was recorded on an Ubuntu running Intel graphics. Maybe the issue with electron is already fixed?
![screenshot from 2018-09-20 20-17-41](https://user-images.githubusercontent.com/2289068/45853296-6d8fc600-bd12-11e8-8dcf-c418505c387c.png)

**Comment by rajivshah3** [comment]
@delki8 could you post the output of `sudo lspci -v | sed -n '/VGA/,/^$/p'`?

**Comment by rajivshah3** [comment]
Also @Brootux is this still reproducible in the latest version (v0.3.5)?

**Comment by Brootux** [comment]
@rajivshah3

Yes, tested with v0.3.5 right now, the problem is still there.

Output of your command is:
```
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09) (prog-if 00 [VGA controller])
	Subsystem: Lenovo 2nd Generation Core Processor Family Integrated Graphics Controller
	Flags: bus master, fast devsel, latency 0, IRQ 28
	Memory at f0000000 (64-bit, non-prefetchable) [size=4M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 5000 [size=64]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
	Capabilities: [d0] Power Management version 2
	Capabilities: [a4] PCI Advanced Features
	Kernel driver in use: i915
	Kernel modules: i915
```
`Lenovo 2nd Generation Core Processor` wtf?

**Comment by Brootux** [comment]
![sysinfo](https://user-images.githubusercontent.com/7403220/45887795-d895d700-bdbc-11e8-9115-f12b85518eb4.png)

**Comment by delki8** [comment]
@rajivshah3 sure,
```
$ sudo lspci -v | sed -n '/VGA/,/^$/p'
00:02.0 VGA compatible controller: Intel Corporation 2nd Generation Core Processor Family Integrated Graphics Controller (rev 09) (prog-if 00 [VGA controller])
	Subsystem: Dell 2nd Generation Core Processor Family Integrated Graphics Controller
	Flags: bus master, fast devsel, latency 0, IRQ 30
	Memory at f0000000 (64-bit, non-prefetchable) [size=4M]
	Memory at e0000000 (64-bit, prefetchable) [size=256M]
	I/O ports at 3000 [size=64]
	[virtual] Expansion ROM at 000c0000 [disabled] [size=128K]
	Capabilities: [90] MSI: Enable+ Count=1/1 Maskable- 64bit-
	Capabilities: [d0] Power Management version 2
	Capabilities: [a4] PCI Advanced Features
	Kernel driver in use: i915
	Kernel modules: i915
```

**Comment by rajivshah3** [comment]
Update: We might have a fix for this soon 🎉 
https://github.com/electron/electron/issues/12820#issuecomment-442638209

**Comment by Brootux** [comment]
Can anyone provide me a appimage with updated electron to >3.0.14 for testing? https://github.com/electron/electron/issues/12820#issuecomment-452702533

**Comment by rajivshah3** [comment]
@Brootux would you mind checking if this is reproducible in the latest version of Trinity? It looks like https://github.com/electron/electron/pull/15555 was included in Electron v3.0.11, which we've been using since v0.4.4.

> Can anyone provide me a appimage with updated electron to >3.0.14 for testing? 

Could you send me an email at rajiv@iota.org? I can email the build to you (since it's not an official build I shouldn't upload it publicly)

**Comment by Brootux** [comment]
Sorry for my late reply, tested with latest stable (0.4.6). The problem seems to be gone for my sytem (ubuntu 18.04, and so on, see above). Probably this issue can be closed.

Thank you

**Comment by rajivshah3** [comment]
Great, thanks for the update!
