### ISSUE TITLE
Password change does not work

### ISSUE THREAD

**Issue by georgmittendorfer** [iotaledger/trinity-wallet#685]
### Bug description

After doing a password change and logging out the new password does not work. The old password still works => the password is not changed.

### Environment Specs

The behaviour was tested on Linux with i3 windown manager.
- OS: Linux 4.18.0-2-amd64 #1 SMP Debian 4.18.10-2 (2018-11-02) x86_64 GNU/Linux
- Trinity version: 0.4.3 Desktop (same issue with 0.4.2).

### Steps To Reproduce

1. Settings -> Change password
2. Type current password into current password field
3. Type new password twice
4. Press Change password
5. Message: Password updated. Your password has been successfully updated.

Close Change password window and exit the application (either log out or quit).
Try to login again: the new password does not work. The old password works.

### Expected behaviour

Password should change.

### Actual behaviour

Password is not changed. Old password still valid.

### Additional Info

There is another bug in the password change dialog that is probably related to this or maybe the reason for this bug: It is possible to use the change password dialog successfully by typing a random text into the current password field.

**Comment by UmbahaSpodPaha** [comment]
Can't reproduce on Win7 v0.4.3 - everything works perfectly on Windows

**Comment by rajivshah3** [comment]
I can't seem to reproduce either issue on macOS Mojave 10.14.1, Trinity v0.4.3. Maybe this is platform specific?

**Comment by UmbahaSpodPaha** [comment]
Also can't reproduce on Linux Mint 19
Trinity 0.4.3

Everything works!

**Comment by georgmittendorfer** [comment]
Well, if it is only a very special case where this is not working then I am relieved and priority is low. I can check the following within the next few days:

* If it is an upgrade issue. Reinstall should fix it then.
* If the cause is the current password, maybe there are some fancy characters.
* If there are permission issues - in what file is the password hash stored locally?

Is it possible for you to type a random text in the current password field and get the 'success' dialog?

Are there some libs on my system for which I should check what versions are installed?

**Comment by rihardsgravis** [comment]
@georgmittendorfer can you confirm that you have a Ledger type account active when trying to update the password?
Edit: If that is the case, I can reproduce and pulled a bugfix

**Comment by georgmittendorfer** [comment]
I can confirm that. At least one account was a ledger account, when I tried to update the password. What do you mean by 'active' - ledger plugged in?

**Comment by georgmittendorfer** [comment]
I can confirm that this was the issue. When selecting a non-ledger account and then changing the password it works. Thanks!

**Comment by t00k** [comment]
This issue is back on 0.5.0, Windows 10. User Thomas L.#5149 on Discord experiencing this exact issue. Also with Ledger account.
